---
- hosts: localhost
  become: true
  tasks:
    - name: install db tools
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3-mysqldb
        - python3-pymysql
        
    - name: install mysql-server
      apt:
        name: mysql-server
        state: latest
        update_cache: yes

    - name: ensure mysql service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: mysql listening on all ports
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regex: ^bind-address
        line: "bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create demo database
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: demo
        state: present
        
    - name: create demo user
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: demo
        password: demo
        priv: 
          'demo.*': 'ALL,GRANT'
        host: '%'
        state: present

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted

